version: '3'

services:
  postgis:
    build: ./postgis
    container_name: sample_map_server_postgis
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - sample_map_server_postgis:/sample_map_server_postgis

volumes:
  sample_map_server_postgis:
