[package]
name = "register_province"
version = "0.1.0"
edition = "2021"

[dependencies]
geojson = "0.23"
serde_json = "1.0"
regex = "1.6"

[dependencies.sqlx]
version = "0.6"
default-features = false
features = ["runtime-tokio-rustls", "macros", "postgres", "uuid", "time"]
